apiVersion: apps/v1
kind: Deployment
metadata:
  name: sweta-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sweta-web
  template:
    metadata:
      labels:
        app: sweta-web
    spec:
      containers:
      - name: sweta-web-node
        image: alexzug89/sweta-web
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:
          - mountPath: app/data
            name: sweta-web-volume
      volumes:
        - name: sweta-web-volume
          persistentVolumeClaim:
            claimName: sweta-web-pvc
